name:                view-trac-tickets
version:             0.1.0.0
github:              "githubuser/view-trac-tickets"
license:             LGPL-3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Fred Hutchinson Cancer Research Center"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/view-trac-tickets#readme>

dependencies:
- base >= 4.7 && < 5
- opaleye


library:
  source-dirs: src

executables:
  view-trac-tickets-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - view-trac-tickets

tests:
  view-trac-tickets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - view-trac-tickets
